version: "3.9"

services:
  mongodb:
    image: mongo:6
    container_name: ecommerce-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./backend/init-products.js:/docker-entrypoint-initdb.d/init-products.js:ro
    environment:
      MONGO_INITDB_DATABASE: ecommerce

  mongo-express:
    image: mongo-express
    container_name: ecommerce-mongo-ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: ecommerce-db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"

